// src/components/EmailModal.jsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheckCircle, faTimesCircle } from '@fortawesome/free-solid-svg-icons';

const EmailModal = () => {
  const [active, setActive] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    const query = new URLSearchParams(location.search);
    setActive(query.get('success') === 'true');
  }, [location.search]);

  const close = () => {
    navigate({ search: '' });
  };

  const query = new URLSearchParams(location.search);
  const success = query.get('success') === 'true';
  const message = query.get('message');
  const error = query.get('error');

  return (
    <div className={`modal ${active ? 'is-active' : ''}`}>
      <div className="modal-background"></div>
      <div className="modal-content box">
        {success ? (
          <div className="success">
            <h1 className="title">
              <FontAwesomeIcon icon={faCheckCircle} /> Message successfully sent!
            </h1>
            <div className="content">
              <p>Thank you! I will reach back to you as soon as possible</p>
            </div>
          </div>
        ) : (
          <div className="error">
            <h1 className="title">
              <FontAwesomeIcon icon={faTimesCircle} /> Uh oh... Message could not be sent
            </h1>
            <div className="content">
              <p>{message}</p>
              <p style={{ color: 'red' }}>{error}</p>
            </div>
          </div>
        )}
        <div className="container">
          <div className="button is-primary" onClick={close}>Ok</div>
        </div>
      </div>
      <button className="modal-close is-large" aria-label="close" onClick={close}></button>
    </div>
  );
};

export default EmailModal;

// src/components/EmailModal.vue
<template>
  <div class="modal" :class="active? 'is-active' : ''">
    <div class="modal-background"></div>
    <div class="modal-content box">
      <div v-if="$route.query.success=='true'" class="success">
        <h1 class="title">
          <fa-icon :icon="['fas','check-circle']" />Message successfully sent!
        </h1>
        <div class="content">
          <p>Thank you! I will reach back to you as soon as possible</p>
        </div>
      </div>
      <div v-else class="error">
        <h1 class="title">
          <fa-icon :icon="['fas','times-circle']" />Uh oh... Message could not be sent
        </h1>
        <div class="content">
          <p>{{$route.query.message}}</p>
          <p style="color:red">{{$route.query.error}}</p>
        </div>
      </div>
      <div class="container">
        <div class="button is-primary" @click="close()">Ok</div>
      </div>
    </div>
    <button class="modal-close is-large" aria-label="close" @click="close()"></button>
  </div>
</template>

<script>
export default {
  title: "email-modal",
  watch: {
    "$route.query": {
      handler(val) {
        if (!!val.success) {
          this.active = true;
        } else {
          this.active = false;
        }
      },
      immediate: true,
      deep: false
    }
  },
  state: {
    query: Object,
    active: Boolean
  },
  methods: {
    close() {
      this.$router.push({ query: {} });
    }
  }
};
</script>
